export const new_products = [
    {
        id: 689,
        name: "冰感機能Polo衫(短袖)",
        style: "D5851",
        image: "images/D5851-98.jpg",
        alt: "冰感機能Polo衫(短袖) / #D5851",
        link: "/products/689",
        size: "M / L / XL / XXL",
        price: "$1,380",
    },
    {
        id: 700,
        name: "冰感機能Polo衫(短袖)",
        style: "D5855",
        image: "images/D5855_98.jpg",
        alt: "冰感機能Polo衫(短袖) / #D5855",
        link: "/products/700",
        size: "M / L / XL",
        price: "$2,160",
    },
    {
        id: 646,
        name: "冰感機能Polo衫(短袖)",
        style: "D4653",
        image: "images/D4653-13.jpg",
        alt: "冰感機能Polo衫(短袖) / #D4653",
        link: "/products/646",
        size: "M / L / XL",
        price: "$1,580",
    },
    {
        id: 586,
        name: "彈性機能Polo衫(短袖)",
        style: "D3256",
        image: "images/D3256-18.jpg",
        alt: "彈性機能Polo衫(短袖) / #D3256",
        link: "/products/586",
        size: "M / L / XL / XXL",
        price: "$1,580",
    },
    {
        id: 517,
        name: "彈性機能Polo衫(短袖)",
        style: "D2055",
        image: "images/D2055-18.jpg",
        alt: "彈性機能Polo衫(短袖) / #D2055",
        link: "/products/517",
        size: "M / L / XL / XXL",
        price: "$1,380",
    },
    {
        id: 448,
        name: "戶外多功能短褲",
        style: "C1721",
        image: "images/C1721-10.jpg",
        alt: "戶外多功能短褲 / #C1721",
        link: "/products/448",
        size: "M / L / XL / XXL",
        price: "$1,380",
    },
    {
        id: 624,
        name: "冰感彈性高球長褲",
        style: "P4680",
        image: "images/P4680-03.jpg",
        alt: "冰感彈性高球長褲 / #P4680",
        link: "/products/624",
        size: "M / L / XL",
        price: "$1,960",
    },
    {
        id: 456,
        name: "彈性剪接束口長褲",
        style: "P1781",
        image: "images/P1781-15.jpg",
        alt: "彈性剪接束口長褲 / #P1781",
        link: "/products/456",
        size: "M / L / XL",
        price: "$1,580",
    },
    {
        id: 390,
        name: "高球戶外休閒長褲",
        style: "PL098",
        image: "images/PL098-10.jpg",
        alt: "高球戶外休閒長褲 / #PL098",
        link: "/products/390",
        size: "M / L / XL",
        price: "$1,780",
    },
    {
        id: 439,
        name: "彈性防曬連帽外套",
        style: "JL175",
        image: "images/JL175-43.jpg",
        alt: "彈性防曬連帽外套 / #JL175",
        link: "/products/439",
        size: "M / L / XL",
        price: "$1,380",
    },
];
