export const new_products = [
    {
        id: 712,
        name: "彈性保暖圓領上衣",
        style: "AL506",
        image: "images/AL506-43.jpg",
        alt: "彈性保暖圓領上衣 / #AL506",
        link: "/products/712",
        size: "M / L / XL",
        price: "$1,380",
    },
    {
        id: 711,
        name: "四面彈剪接長褲(薄款)",
        style: "PL591",
        image: "images/PL591-10.jpg",
        alt: "四面彈剪接長褲(薄款) / #PL591",
        link: "/products/711",
        size: "M / L / XL",
        price: "$1,580",
    },
    {
        id: 403,
        name: "立領輕鋪棉背心",
        style: "HL039",
        image: "images/HL039_13.jpg",
        alt: "立領輕鋪棉背心 / #HL039",
        link: "/products/403",
        size: "M / L / XL",
        price: "$1,580",
    },
    {
        id: 467,
        name: "彈性保暖圓領上衣",
        style: "AL106",
        image: "images/AL10673.jpg",
        alt: "彈性保暖圓領上衣 / #AL106",
        link: "/products/467",
        size: "M / L / XL",
        price: "$1,180",
    },
    {
        id: 463,
        name: "棉質內刷毛圓領長袖上衣",
        style: "FL116",
        image: "images/FL116-47.jpg",
        alt: "棉質內刷毛圓領長袖上衣 / #FL116",
        link: "/products/463",
        size: "M / L / XL",
        price: "$1,380",
    },
    {
        id: 665,
        name: "雙面穿絨毛立領外套",
        style: "JL365",
        image: "images/JL365-43.jpg",
        alt: "雙面穿絨毛立領外套 / #JL365",
        link: "/products/665",
        size: "M / L / XL",
        price: "$1,780",
    },
    {
        id: 621,
        name: "四面彈束口長褲(薄款)",
        style: "PL390",
        image: "images/PL390-93.jpg",
        alt: "四面彈束口長褲(薄款) / #PL390",
        link: "/products/621",
        size: "M / L / XL",
        price: "$1,580",
    },
    {
        id: 615,
        name: "彈性防風長褲(磨毛裏)",
        style: "PL392",
        image: "images/PL392-10.jpg",
        alt: "彈性防風長褲(磨毛裏) / #PL392",
        link: "/products/615",
        size: "M / L / XL",
        price: "$1,780",
    },
    {
        id: 611,
        name: "立領鋪棉外套",
        style: "HL338",
        image: "images/HL338-03.jpg",
        alt: "立領鋪棉外套 / #HL338",
        link: "/products/611",
        size: "M / L / XL",
        price: "$2,760",
    },
    {
        id: 485,
        name: "可拆帽鋪棉外套(長版)",
        style: "HL138",
        image: "images/HL138-10.jpg",
        alt: "可拆帽鋪棉外套(長版) / #HL138",
        link: "/products/485",
        size: "M / L / XL",
        price: "$2,980",
    },
    {
        id: 486,
        name: "可拆帽鋪棉外套",
        style: "HL137",
        image: "images/HL137-43.jpg",
        alt: "可拆帽鋪棉外套 / #HL137",
        link: "/products/486",
        size: "M / L / XL",
        price: "$2,580",
    },
]
