export const new_products = [
    {
        id: 715,
        name: "男性機能內搭褲",
        style: "A5905",
        image: "images/A5905-10.jpg",
        alt: "男性機能內搭褲 / #A5905",
        link: "/detail?id=715",
        size: "M / L / XL",
        price: "$1,380",
    },
    {
        id: 714,
        name: "彈性保暖圓領上衣",
        style: "A5901",
        image: "images/A5901-10.jpg",
        alt: "彈性保暖圓領上衣 / #A5901",
        link: "/detail?id=714",
        size: "M / L / XL",
        price: "$1,380",
    },
    {
        id: 708,
        name: "彈性保暖圓領上衣",
        style: "A5902",
        image: "images/A5902-13.jpg",
        alt: "彈性保暖圓領上衣 / #A5902",
        link: "/detail?id=708",
        size: "M / L / XL",
        price: "$1,380",
    },
    {
        id: 710,
        name: "四面彈剪接長褲(薄款)",
        style: "P5970",
        image: "images/P5970-10.jpg",
        alt: "四面彈剪接長褲(薄款) / #P5970",
        link: "/detail?id=710",
        size: "M / L / XL / XXL",
        price: "$1,580",
    },
    {
        id: 707,
        name: "棉質內刷毛縮口長褲",
        style: "P5977",
        image: "images/P5977-10.jpg",
        alt: "棉質內刷毛縮口長褲 / #P5977",
        link: "/detail?id=707",
        size: "M / L / XL",
        price: "$1,580",
    },
    {
        id: 616,
        name: "雙面穿立領鋪棉背心",
        style: "H3335",
        image: "images/H3335-15.jpg",
        alt: "雙面穿立領鋪棉背心 / #H3335",
        link: "/detail?id=616",
        size: "M / L / XL",
        price: "$1,780",
    },
    {
        id: 405,
        name: "立領輕鋪棉背心",
        style: "H0635",
        image: "images/H0635-93.jpg",
        alt: "立領輕鋪棉背心 / #H0635",
        link: "/detail?id=405",
        size: "M / L / XL",
        price: "$1,580",
    },
    {
        id: 401,
        name: "立領輕鋪棉背心",
        style: "H0636",
        image: "images/H0636-10.jpg",
        alt: "立領輕鋪棉背心 / #H0636",
        link: "/detail?id=401",
        size: "M / L / XL",
        price: "$1,780",
    },
    {
        id: 662,
        name: "彈性保暖圓領上衣",
        style: "A4701",
        image: "images/A4701-93.jpg",
        alt: "彈性保暖圓領上衣 / #A4701",
        link: "/detail?id=662",
        size: "M / L / XL",
        price: "$1,380",
    },
    {
        id: 666,
        name: "棉質內刷毛束口長褲",
        style: "P3377",
        image: "images/P3377-17.jpg",
        alt: "棉質內刷毛束口長褲 / #P3377",
        link: "/detail?id=666",
        size: "M / L / XL",
        price: "$1,580",
    },
    {
        id: 609,
        name: "彈性保暖圓領上衣",
        style: "A3301",
        image: "images/A3301-10.jpg",
        alt: "彈性保暖圓領上衣 / #A3301",
        link: "/detail?id=609",
        size: "M / L / XL",
        price: "$1,380",
    },
    {
        id: 613,
        name: "彈性圓領長袖上衣",
        style: "F3311",
        image: "images/F3311-18.jpg",
        alt: "彈性圓領長袖上衣 / #F3311",
        link: "/detail?id=613",
        size: "M / L / XL",
        price: "$1,380",
    },
    {
        id: 673,
        name: "彈性圓領上衣(長袖)",
        style: "D3308",
        image: "images/D3308-98.jpg",
        alt: "彈性圓領上衣(長袖) / #D3308",
        link: "/detail?id=673",
        size: "M / L / XL",
        price: "$1,380",
    },
    {
        id: 618,
        name: "連帽四面彈外套(薄款)",
        style: "J3350",
        image: "images/J3350-15.jpg",
        alt: "連帽四面彈外套(薄款) / #J3350",
        link: "/detail?id=618",
        size: "M / L / XL",
        price: "$1,780",
    },
    {
        id: 619,
        name: "連帽防風外套(網裏)",
        style: "J3351",
        image: "images/J3351-15.jpg",
        alt: "連帽防風外套(網裏) / #J3351",
        link: "/detail?id=619",
        size: "M / L / XL",
        price: "$1,960",
    },
    {
        id: 617,
        name: "可拆帽防風外套(磨毛裏)",
        style: "J3352",
        image: "images/J3352-60.jpg",
        alt: "可拆帽防風外套(磨毛裏) / #J3352",
        link: "/detail?id=617",
        size: "M / L / XL / XXL",
        price: "$2,360",
    },
    {
        id: 622,
        name: "可拆帽衝鋒外套(搖粒絨裏)",
        style: "J3353",
        image: "images/J3353-60.jpg",
        alt: "可拆帽衝鋒外套(搖粒絨裏) / #J3353",
        link: "/detail?id=622",
        size: "M / L / XL",
        price: "$2,760",
    },
    {
        id: 608,
        name: "雙面穿絨毛立領外套",
        style: "J3355",
        image: "images/J3355-97.jpg",
        alt: "雙面穿絨毛立領外套 / #J3355",
        link: "/detail?id=608",
        size: "M / L / XL",
        price: "$1,780",
    },
    {
        id: 612,
        name: "可拆帽鋪棉外套",
        style: "H3331",
        image: "images/H3331-16.jpg",
        alt: "可拆帽鋪棉外套 / #H3331",
        link: "/detail?id=612",
        size: "M / L / XL",
        price: "$3,360",
    },
    {
        id: 476,
        name: "立領鋪棉背心",
        style: "H1935",
        image: "images/H1935-10.jpg",
        alt: "立領鋪棉背心 / #H1935",
        link: "/detail?id=476",
        size: "M / L / XL",
        price: "$1,960",
    },
]
